sunnankar/tudaa

index.html
pricechecker.html

Description
Clean up html layout and use JS map to build elements. This displays all json nodes without the need to manually set the index.

Clean up html layout

---

index.html
pricechecker.html

This pull request is to address the bugs in the main branch

Btc price list

---

README.md
_frontend/components/indexes.js
_frontend/entrypoints/application.js
_site/index.html
index.md
indexes.html

Price Index Project View

---

index.md

index.md price index update

---

index.md

reverted back to old url

---

index.md

push new path

---

_frontend/components/indexes.js

push for cumulative difficulty

push for cumulative difficulty

---

_frontend/components/indexes.js

add websocet link

---

indexes.html

first new view

---

_frontend/components/indexes.js

updated JS script

---

_frontend/components/indexes.js
indexes.html

Test view link 1

---

indexes.html

date interval

---

_frontend/components/indexes.js

fetch interval

---

_frontend/components/indexes.js
indexes.html

new dict interval

---

indexes.html

if the 2 hour has not trades

---

indexes.html

This reverts commit 6f21e3e173a38dace179916d5ec68766e0e30013.

Revert "if the 2 hour has not trades"

---

indexes.html

Grin blockchain deploy 1

---

_frontend/components/indexes.js

display volume

---

_frontend/components/indexes.js

log volume data

---

_frontend/components/indexes.js
indexes.html

display volume data

---

_frontend/components/indexes.js
indexes.html

This reverts commit bc73bb59df139212f3732641220e659f40819687.

Revert "display volume data"

---

_frontend/components/indexes.js
_site/index.html
indexes.html

Cumulative Volume

---

_frontend/components/indexes.js
_site/index.html

MWC-USDT Spot Price Data

---

_frontend/components/indexes.js
indexes.html

fetchMovingAverage

---

_frontend/components/indexes.js
_site/index.html

fetchOneQuarterDifficulty

---

_frontend/components/indexes.js
_site/index.html

fix one Quarter bug

---

_frontend/components/indexes.js
_site/index.html

remove single difficulty

---

_frontend/components/indexes.js
_site/index.html
indexes.html

remove vwap interval
